title: Bo Kolstrup
logo: /asset/Bo-Kolstrup.png
description: "Científico de Datos con experiencia en modelos predictivos y análisis de datos"

#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
